DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
    userID VARCHAR(20), 
    name VARCHAR(30),
    email VARCHAR(60),
    pwd VARCHAR(20),
    PRIMARY KEY (userID)
);

DROP TABLE IF EXISTS Tweets;
CREATE TABLE Tweets(
    tweetID INT NOT NULL AUTO_INCREMENT, 
    tweet VARCHAR(140),
    time_stamp TIMESTAMP,
    userID VARCHAR(20),
    PRIMARY KEY (tweetID)
    -- FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Messages;
CREATE TABLE Messages(
    messageID INT NOT NULL, 
    text VARCHAR(140),
    time_stamp TIMESTAMP NOT NULL,
    senderID VARCHAR(20),
    receiverID VARCHAR(20),
    PRIMARY KEY (messageID)
    -- FOREIGN KEY (senderID) REFERENCES Users(userID) ON DELETE NO ACTION ON UPDATE CASCADE,
    -- FOREIGN KEY (receiverID) REFERENCES Users(userID) ON DELETE NO ACTION ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Retweet;
CREATE TABLE Retweet(
    tweetID INT,
    userID VARCHAR(20),
    PRIMARY KEY (tweetID, userID) 
    -- FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Likes;
CREATE TABLE Likes
(
    tweetID INT,
    userID VARCHAR(20),
    PRIMARY KEY (tweetID, userID)
    -- FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE,
    -- FOREIGN KEY (tweetID) REFERENCES Tweets(tweetID) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Reply;
CREATE TABLE Reply
(
    commentID INT,
    beCommentedID INT, 
    PRIMARY KEY (commentID, beCommentedID)
    -- FOREIGN KEY (commentID) REFERENCES Tweets(tweetID) ON DELETE CASCADE ON UPDATE CASCADE,
    -- FOREIGN KEY (beCommentedID) REFERENCES Tweets(tweetID) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Follows;
CREATE TABLE Follows
(
  followerID VARCHAR(20),
  leaderID VARCHAR(20),
  PRIMARY KEY (followerID, leaderID)
  -- FOREIGN KEY (followerID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE,
  -- FOREIGN KEY (leaderID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);
